name: Secretlint
# https://github.com/secretlint/secretlint/issues/166
on: [pull_request, workflow_dispatch]

# secretlint + git diff on Pull Request
# https://github.com/secretlint/secretlint

jobs:
  test:
    name: "Secretlint"
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v4
      - name: run secretlint command on docker
        uses: addnab/docker-run-action@v3
        with:
          # https://hub.docker.com/r/secretlint/secretlint/tags
          image: secretlint/secretlint:v5.1.1
          options: >
            --rm -v ${{ github.workspace }}:/opt
            -w=/opt
          shell: bash
          run: secretlint ${{ env.GIT_DIFF_FILTERED }}
        if: env.GIT_DIFF && !env.MATCHED_FILES
      - name: echo
        run: |
          echo "GIT_DIFF_FILTERED: ${{ env.GIT_DIFF_FILTERED }}"
          echo "##########"
          echo "GIT_DIFF: ${{ env.GIT_DIFF }}"
          echo "##########"
          echo "MATCHED_FILES: ${{ env.MATCHED_FILES }}"
          echo "##########"
