name: Secretlint
# https://github.com/secretlint/secretlint/issues/166
on: [pull_request, workflow_dispatch]

# secretlint + git diff on Pull Request
# https://github.com/secretlint/secretlint

jobs:
  test:
    name: "Secretlint"
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v4
      - name: setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install
        run: npm install
      - name: Lint with Secretlint
        run: npx --no-install secretlint ${{ env.GIT_DIFF_FILTERED }}
        if: env.GIT_DIFF && !env.MATCHED_FILES


  $ docker run --rm -v "$PWD:$PWD" -w="$PWD" \
  --entrypoint yq linuxserver/yq \
  <yqコマンド>
